
POST http://localhost:10001/users/
Accept: application/json
Content-Type: application/json

{
	"username": "ivan",
	"password": "qwerty",
	"role": "admin"
}

###

POST http://localhost:10001/users/
Accept: application/json
Content-Type: application/json

{
	"username": "vasya",
	"password": "my_little_pony",
	"role": "user"
}

###

POST http://localhost:10001/users/
Accept: application/json
Content-Type: application/json

{
	"username": "oleg",
	"password": "qwerty",
	"role": "user"
}

###

POST http://localhost:10001/users/
Accept: application/json
Content-Type: application/json

{
	"username": "oleg",
	"password": "P@ssw0rd",
	"role": "admin"
}

###

POST http://localhost:10001/auth/
Accept: application/json
Content-Type: application/json

{
	"username": "ivan",
	"password": "qwerty"
}

###

POST http://localhost:10001/auth/
Accept: application/json
Content-Type: application/json

{
	"username": "oleg",
	"password": "qwerty"
}

###

GET http://127.0.0.1:10001/movies/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzIzMjI1OH0.UMYcG3vmR3MDh4GX5v5onUMSLZG5NGR-DyEjquO0wdg

###

GET http://127.0.0.1:10001/movies/?director_id=12
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzIzMjI1OH0.UMYcG3vmR3MDh4GX5v5onUMSLZG5NGR-DyEjquO0wdg
###

GET http://127.0.0.1:10001/movies/?genre_id=4
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzIzMjI1OH0.UMYcG3vmR3MDh4GX5v5onUMSLZG5NGR-DyEjquO0wdg
###

GET http://127.0.0.1:10001/movies/?year=2010
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzIzMjI1OH0.UMYcG3vmR3MDh4GX5v5onUMSLZG5NGR-DyEjquO0wdg
###

GET http://127.0.0.1:10001/directors/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzIzMjI1OH0.UMYcG3vmR3MDh4GX5v5onUMSLZG5NGR-DyEjquO0wdg
###

GET http://127.0.0.1:10001/directors/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzIzMjI1OH0.UMYcG3vmR3MDh4GX5v5onUMSLZG5NGR-DyEjquO0wdg
###

GET http://127.0.0.1:10001/genres/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzIzMjI1OH0.UMYcG3vmR3MDh4GX5v5onUMSLZG5NGR-DyEjquO0wdg
###

GET http://127.0.0.1:10001/genres/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzIzMjI1OH0.UMYcG3vmR3MDh4GX5v5onUMSLZG5NGR-DyEjquO0wdg
###

GET http://127.0.0.1:10001/movies/21
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzIzMjI1OH0.UMYcG3vmR3MDh4GX5v5onUMSLZG5NGR-DyEjquO0wdg
###

POST http://127.0.0.1:10001/movies/
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NTcyMzIxMTJ9.m9Hca2104aReI-EMBYGub7V6EetlopiSCxac6AeVR3M

{
  "title": "Гарри Поттер мой кумир!",
  "trailer": "таким фильмам не нужны трейлеры",
  "year": 1990,
  "rating": 10,
  "description": "10 из 10!"
}

###

PUT http://127.0.0.1:10001/movies/21
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NTcyMzIxMTJ9.m9Hca2104aReI-EMBYGub7V6EetlopiSCxac6AeVR3M

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

PATCH http://127.0.0.1:10001/movies/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NTcyMzIxMTJ9.m9Hca2104aReI-EMBYGub7V6EetlopiSCxac6AeVR3M

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

DELETE http://127.0.0.1:10001/movies/21
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NTcyMzIxMTJ9.m9Hca2104aReI-EMBYGub7V6EetlopiSCxac6AeVR3M
